name: DevOps Tracking

on:
  push:
    branches:
      - main

jobs:
  tracking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Collect tracking data
        env:
          DEVOPS_TRACKING_SECRETS: ${{ secrets.DEVOPS_TRACKING_SECRETS }}
        run: bash bin/devops-tracking release
